### PR TITLE
Move to wasm-pack and other WASM build refactoring

### PR DESCRIPTION
**Pull request by ishitatsuyuki**
Merry Christmas!

Some technical debts:

- A `target` symlink is included until support of workspace is implemented.
- The Material design related libraries and icons are not actively getting developed. We probably want to move to our own CSS design at some point.

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
TODO: get wasm-pack into the CI environment.

**Comment by ishitatsuyuki** [comment]
I'm planning to add GitHub pages deployment sometime soon. To proceed, I need someone with privileges to do the following:

- Decide which repository we would publish the pages and setup (configure) GitHub pages. It could be a branch of this repository, or a new organization-wide repository.
- Obtain a token with push access. This could be:
  - Personal access token with your account
  - Personal access token with a new bot account
  - A token for a new private GitHub app (not tested)
  
  Then, add this token privately to Travis CI's environment as `GH_TOKEN`.

**Comment by cmtt** [comment]
Thank you for the update. This is a good starting point for some UI updates after this PR has been merged.
@maciejhirsz, I'd propose to deploy the wasm build in a `gh-pages` branch until there is a website to integrate it into. Can you take it from here?

**Comment by ishitatsuyuki** [comment]
@cmtt Is there anything left to review, or you're just waiting for @maciejhirsz's approval?

**Pull request merged**
